public class denemeCls {
    public void method1(){
        string araba = 'audi';
        system.debug('my car is '+araba);

    }

    public void method2(string araba1){
        
        system.debug('my car is '+araba1);
        
    }
    public string method3(string araba2){
        system.debug('today,weather is so amazing.');
        return araba2;
    }
    public string araba3='';
    public string method4(string a){
        return a;
    }
    private string araba4 ='mercedes';
    public void method5(){
        system.debug(araba4);

    }
    public string method6(){
        return araba4;
    }
    public string method7(string carss){
        carss+=carss;
        return araba4;
    }

}
