public class mathematicalClass {
    public Integer addition(Integer a,Integer b){
        Integer sum = a+b;
        return sum;
    }
    public integer subtraction(integer a,Integer b){
        Integer sub = a-b;
        return sub;
    }
    public Integer multiplication(Integer a,Integer b){
        Integer mul = a*b;
        return mul;
    }
    public Decimal division(Decimal a,Decimal b){
        Decimal div = a/b;
        return div;
    }
   
}
