public class primitiveDataTypeDemo {
    public void primitiveDataType(){
        Object obj = ' This is a string ';
        Object obj2 = 10;
        ID id1 = '0018c00002Eub8QAAR';
        system.debug(obj);
        system.debug(obj2);
        system.debug(id1);

        // Decimal decValue = 27.01;
        // system.debug('Decimal: ' + decValue);

        // Long longvalue =  2147483648L;
        // system.debug('Long: ' + longvalue);



    //     string batchName = 'Falcons';
    //     Integer totalCandidates = 120;
    //     Boolean isAdminCompleted = true;

    //    string batchDescription = batchName + ' are the best.';
    //    system.debug(batchDescription);

        // system.debug('batch name is' +batchName);
        // system.debug('total # of candidates:' +totalCandidates);
        // system.debug('admin completed?' +isAdminCompleted);
                

    }

}
