mathematicalClass mth = new mathematicalClass();
integer sumOfNumbers = mth.addition(13, 56);
system.debug('Total number is '+sumOfNumbers);

Integer subOfNumber = mth.subtraction(20,2 );
system.debug('subtraction of numbers is '+ subOfNumber);

Integer mulOfNumbers = mth.multiplication(20, 11);
system.debug('Multiplication is '+mulOfNumbers);

Decimal divOfNumbers = mth.division(5, 2);
system.debug('division is ' + divOfNumbers);

